os: linux
group: stable
sudo: required
dist: bionic
services:
    - docker
language: generic
python:
    - "2.7"
before_install:
    # Install Google Protobuf Libraries
    - sudo apt-get install libprotobuf-dev libprotoc-dev protobuf-compiler
    - sudo apt-get install python-pip
    - sudo pip2 install protobuf

install:
    # Install ROS
    # Refelence: http://wiki.ros.org/melodic/Installation/Ubuntu
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
    - sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
    - sudo apt-get update -qq
    - sudo apt-get install ros-melodic-desktop-full -y
    - sudo apt-get install ros-melodic-navigation
    - sudo rosdep init
    - rosdep update
    - echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
    - source ~/.bashrc

    # Copy Sciurus packages to /catkin_ws/src
    - mkdir -p ~/catkin_ws/src/
    - rsync -a ./ ~/catkin_ws/src/consai2
    - cd ~/catkin_ws/src/
    - catkin_init_workspace 
    - rosdep install -r -y --from-paths . --ignore-src
    - cd ..
    - catkin_make
    - echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
    - source ~/.bashrc

script:
    # Code level tests
    - catkin_make run_tests # Always returns 0
    - catkin_test_results   # Output previous test results
    # ROS WTF tests
    - cd ~/catkin_ws/src/consai2
    - roswtf ./consai2_examples/launch/control_example.launch
    - roswtf ./consai2_examples/launch/joystic_example.launch
    - roswtf ./consai2_examples/launch/visualizer.launch

